---
version: 0.2
env:
  shell: bash
  variables:
    RDS_CA_CERT_URL: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    MYSQL_USER_TO_CREATE: iam
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.x
    commands:
      - set -euo pipefail
      - echo 'Install phase is started.'
      - dnf -y upgrade
      - dnf -y install aws-cli jq mariadb105 update-ca-trust
    finally:
      - aws --version
      - jq --version
      - mysql --version
      - echo 'Install phase is completed.'
  pre_build:
    on-failure: ABORT
    commands:
      - set -euo pipefail
      - echo 'Pre-build phase is started.'
      - curl -sSL -o "/etc/pki/ca-trust/source/anchors/${RDS_CA_CERT_URL##*/}" "${RDS_CA_CERT_URL}"
      - update-ca-trust
    finally:
      - echo 'Pre-build phase is completed.'
  build:
    on-failure: ABORT
    commands:
      - set -euo pipefail
      - echo 'Build phase is started.'
      - echo
      - |
        cat <<EOF | tee /tmp/create-iam-auth-user-and-database.sql
        CREATE USER IF NOT EXISTS '${MYSQL_USER_TO_CREATE}' IDENTIFIED WITH AWSAuthenticationPlugin AS 'RDS';
        GRANT ALL PRIVILEGES ON *.* TO ${MYSQL_USER_TO_CREATE};
        FLUSH PRIVILEGES;
        CREATE DATABASE IF NOT EXISTS ${RDS_CLUSTER_DATABASE_NAME};
        EOF
      - echo
      - >
        aws secretsmanager get-secret-value
        --secret-id "${RDS_CLUSTER_SECRETS_MANAGER_SECRET_ARN}"
        --query 'SecretString'
        --output text
        | jq -r '.password'
        | xargs -I{} mysql
        --host "${RDS_CLUSTER_ENDPOINT}"
        --port "${RDS_CLUSTER_PORT}"
        --user "${RDS_CLUSTER_USERNAME}"
        --password '{}'
        --execute 'source /tmp/create-iam-auth-user-and-database.sql'
    finally:
      - echo 'Build phase is completed.'
  post_build:
    on-failure: ABORT
    commands:
      - set -euo pipefail
      - echo 'Post-build phase is started.'
      - echo
      - |
        cat <<EOF | tee /tmp/show-users-and-databases.sql
        SELECT user, host FROM mysql.user;
        SHOW DATABASES;
        EOF
      - echo
      - >
        aws rds generate-db-auth-token
        --hostname "${RDS_CLUSTER_ENDPOINT}"
        --port "${RDS_CLUSTER_PORT}"
        --username "${MYSQL_USER_TO_CREATE}"
        | xargs -I{} mysql
        --host "${RDS_CLUSTER_INSTANCE_ENDPOINT}"
        --port "${RDS_CLUSTER_PORT}"
        --user "${MYSQL_USER_TO_CREATE}"
        --password '{}'
        --execute 'source /tmp/show-users-and-databases.sql'
    finally:
      - echo 'Post-build phase is completed.'
